# dockerfile.frontend
FROM node:23.7.0

WORKDIR /usr/src/app

COPY frontend/package.json frontend/yarn.lock ./
COPY frontend/ ./frontend/
COPY webpack.config.js ./

RUN yarn install
RUN yarn add @babel/preset-env @babel/preset-react --dev

EXPOSE 3001

CMD ["yarn", "start"]
